trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello World
  displayName: 'Run Hello World script'

- task: AzureCLI@2
    displayName: "AZ Group List"
    inputs:
      azureSubscription: pictephone
      scriptType: bash
      addSpnToEnvironment: true
      scriptLocation: inlineScript
      inlineScript: |
        az group list
